const AWSXRay = require("aws-xray-sdk-core");
const AWS = AWSXRay.captureAWS(require("aws-sdk"));


exports.handler = async function (event, context) {
  const data = [
    {
      _id: "5f1b71105bbfe7720eee829c",
      index: 0,
      guid: "a6a99888-51de-4496-8183-1de8f7e1f9f3",
      isActive: false,
      balance: "$3,901.36",
      picture: "http://placehold.it/32x32",
      age: 20,
      eyeColor: "blue",
      name: "Bobbie Wynn",
      gender: "female",
      company: "COMCUR",
      email: "bobbiewynn@comcur.com",
      phone: "+1 (889) 571-2830",
      address: "186 Lefferts Avenue, Sylvanite, Idaho, 5153",
      about:
        "Dolor officia proident aliqua nisi et magna officia elit nostrud sit non. Laborum excepteur elit nulla est fugiat amet et consectetur ad. Irure esse eu exercitation nulla dolore do do consectetur nulla pariatur excepteur dolor excepteur id.\r\n",
      registered: "2014-03-27T02:43:40 +06:00",
      latitude: -7.113154,
      longitude: -47.359781,
      tags: ["ea", "esse", "cillum", "esse", "deserunt", "sit", "ut"],
      friends: [
        {
          id: 0,
          name: "Oneil Crosby",
        },
        {
          id: 1,
          name: "Craft Mullins",
        },
        {
          id: 2,
          name: "Vincent Barrett",
        },
      ],
      greeting: "Hello, Bobbie Wynn! You have 5 unread messages.",
      favoriteFruit: "apple",
    },
    {
      _id: "5f1b7110c80ccdf2c490aa10",
      index: 1,
      guid: "b33b454a-f0d6-4307-b72f-823549ca599c",
      isActive: false,
      balance: "$3,524.50",
      picture: "http://placehold.it/32x32",
      age: 23,
      eyeColor: "brown",
      name: "Wall Ball",
      gender: "male",
      company: "ZILODYNE",
      email: "wallball@zilodyne.com",
      phone: "+1 (970) 485-2997",
      address: "651 Lloyd Street, Needmore, Arizona, 1477",
      about:
        "Labore non laboris reprehenderit exercitation aute minim. In exercitation reprehenderit eu ut labore ullamco non. Ad reprehenderit velit magna culpa laboris proident laboris consectetur pariatur. Commodo laborum incididunt cillum elit incididunt culpa sunt consectetur dolore in. Enim voluptate laborum laborum ipsum cillum sit deserunt proident velit est ullamco dolor consectetur culpa. Consectetur amet et ad excepteur nisi sint exercitation quis.\r\n",
      registered: "2017-01-03T03:55:24 +06:00",
      latitude: -41.088763,
      longitude: 20.679262,
      tags: ["pariatur", "est", "esse", "ut", "dolore", "aliqua", "sunt"],
      friends: [
        {
          id: 0,
          name: "Courtney Kent",
        },
        {
          id: 1,
          name: "Dominique Stout",
        },
        {
          id: 2,
          name: "Rachael Crane",
        },
      ],
      greeting: "Hello, Wall Ball! You have 6 unread messages.",
      favoriteFruit: "strawberry",
    },
    {
      _id: "5f1b711092664061d6cc056b",
      index: 2,
      guid: "7e6316bf-4e82-4033-b1b5-f85e139f7b8b",
      isActive: true,
      balance: "$2,865.68",
      picture: "http://placehold.it/32x32",
      age: 33,
      eyeColor: "blue",
      name: "Luna Harmon",
      gender: "male",
      company: "GLASSTEP",
      email: "lunaharmon@glasstep.com",
      phone: "+1 (979) 565-3528",
      address: "537 Berry Street, Carrizo, Kansas, 1784",
      about:
        "Proident ullamco do dolore consectetur laborum velit Lorem cillum nisi exercitation dolore. Magna eiusmod nisi commodo labore dolor excepteur. Aliqua occaecat fugiat irure elit sunt Lorem sint amet in. Quis dolore sit labore proident elit magna. Elit eiusmod magna excepteur nulla officia tempor culpa amet. Consectetur ad proident fugiat ut.\r\n",
      registered: "2019-06-09T08:57:16 +05:00",
      latitude: 72.564607,
      longitude: -59.568112,
      tags: ["sint", "officia", "qui", "magna", "ea", "irure", "cupidatat"],
      friends: [
        {
          id: 0,
          name: "Cortez Macias",
        },
        {
          id: 1,
          name: "Stewart Fisher",
        },
        {
          id: 2,
          name: "Stephens Bell",
        },
      ],
      greeting: "Hello, Luna Harmon! You have 6 unread messages.",
      favoriteFruit: "apple",
    },
    {
      _id: "5f1b7110ed1c360989a2187d",
      index: 3,
      guid: "70e8e86f-f516-4568-8b08-c9ea2b7dfc11",
      isActive: false,
      balance: "$1,952.11",
      picture: "http://placehold.it/32x32",
      age: 37,
      eyeColor: "brown",
      name: "Hill Kane",
      gender: "male",
      company: "FROLIX",
      email: "hillkane@frolix.com",
      phone: "+1 (831) 510-2458",
      address: "901 Batchelder Street, Condon, South Dakota, 3645",
      about:
        "Irure ad ad et exercitation. Ex anim cupidatat nostrud duis aliqua sunt dolore et Lorem. Ad quis irure eu magna aute exercitation anim laborum velit irure. Amet exercitation eu enim deserunt.\r\n",
      registered: "2020-06-24T08:29:37 +05:00",
      latitude: 57.201607,
      longitude: -64.342869,
      tags: [
        "ipsum",
        "exercitation",
        "commodo",
        "laborum",
        "culpa",
        "sunt",
        "nostrud",
      ],
      friends: [
        {
          id: 0,
          name: "Effie Taylor",
        },
        {
          id: 1,
          name: "Cooper Mitchell",
        },
        {
          id: 2,
          name: "Carlson Melendez",
        },
      ],
      greeting: "Hello, Hill Kane! You have 8 unread messages.",
      favoriteFruit: "strawberry",
    },
    {
      _id: "5f1b7110bc59658f812a6bdb",
      index: 4,
      guid: "71fb9496-40ed-42fe-a38f-c46ff517f1de",
      isActive: true,
      balance: "$1,007.84",
      picture: "http://placehold.it/32x32",
      age: 27,
      eyeColor: "green",
      name: "Shaffer English",
      gender: "male",
      company: "CINASTER",
      email: "shafferenglish@cinaster.com",
      phone: "+1 (857) 543-2964",
      address: "359 Beaumont Street, Kenmar, Mississippi, 8477",
      about:
        "Amet elit laborum velit tempor amet eu sint. Dolor amet incididunt Lorem do veniam cupidatat commodo mollit eu dolore enim adipisicing ex non. Dolore reprehenderit minim sunt veniam excepteur non ad exercitation. Duis fugiat nulla excepteur est pariatur quis fugiat anim culpa occaecat in ipsum. Culpa Lorem ut proident aute ullamco sint consectetur occaecat sint ipsum ullamco tempor occaecat. Elit veniam in elit ad amet commodo enim.\r\n",
      registered: "2015-04-19T11:57:16 +05:00",
      latitude: -88.181519,
      longitude: -2.087476,
      tags: ["anim", "quis", "aliqua", "non", "amet", "velit", "laborum"],
      friends: [
        {
          id: 0,
          name: "Ethel Casey",
        },
        {
          id: 1,
          name: "Antoinette Faulkner",
        },
        {
          id: 2,
          name: "Simon Bishop",
        },
      ],
      greeting: "Hello, Shaffer English! You have 1 unread messages.",
      favoriteFruit: "apple",
    },
    {
      _id: "5f1b7110a7a8c7aaf75e0d04",
      index: 5,
      guid: "796aafac-65dc-4e29-abf7-b7465b688555",
      isActive: true,
      balance: "$1,291.84",
      picture: "http://placehold.it/32x32",
      age: 38,
      eyeColor: "green",
      name: "Cameron Maddox",
      gender: "male",
      company: "EXTRAWEAR",
      email: "cameronmaddox@extrawear.com",
      phone: "+1 (923) 434-3066",
      address: "211 Oxford Walk, Corriganville, Virginia, 3137",
      about:
        "Tempor exercitation consectetur excepteur esse et qui magna eiusmod occaecat minim sunt nulla irure. Lorem duis enim sit id ipsum occaecat. Laboris dolore consectetur qui eu proident magna sunt incididunt consequat. Excepteur aliqua excepteur occaecat pariatur nisi occaecat Lorem pariatur sit eu. Est aliqua incididunt amet culpa sit.\r\n",
      registered: "2014-02-02T04:51:50 +06:00",
      latitude: 59.461338,
      longitude: 28.89989,
      tags: [
        "reprehenderit",
        "eiusmod",
        "officia",
        "ad",
        "dolore",
        "ut",
        "laboris",
      ],
      friends: [
        {
          id: 0,
          name: "Alta Hurst",
        },
        {
          id: 1,
          name: "Deborah Stokes",
        },
        {
          id: 2,
          name: "Tate Chambers",
        },
      ],
      greeting: "Hello, Cameron Maddox! You have 4 unread messages.",
      favoriteFruit: "strawberry",
    },
  ];

  return {
    statusCode: 200,
    headers: {
      "Access-Control-Allow-Origin": "*",
    },
    body: JSON.stringify(data),
    isBase64Encoded: false,
  };
};
